# Generated by Django 5.2.11 on 2026-03-04 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0086_gfk_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='asn',
            name='role',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asns', to='ipam.role'
            ),
        ),
    ]
